services:
  bot:
    container_name: detoxy-discord-bot
    build:
      context: ./bot
    image: detoxy-discord-bot:latest
    env_file:
      - ./bot/.env
    depends_on:
      model:
        condition: service_healthy
        restart: true

  model:
    container_name: detoxy-model-api
    build:
      context: ./model
    image: detoxy-model-api:latest
    env_file:
      - ./model/.env
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      start_period: 45s
      interval: 30s
      retries: 3
      timeout: 5s