[project]
name = "toxy-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "anitamaxvim", email = "107803920+anitamaxvim@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.3.10",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "scikit-learn>=1.6.1",
    "scikit-multilearn>=0.2.0",
    "tensorflow==2.15.1",
]

[tool.pyright]
venvPath = "."
venv = "venv"

[project.scripts]
toxy-bot = "toxy_bot:main"
pipeline = "toxy_bot.ml.data.pipeline:run_pipeline"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
