[project]
name = "detoxy"
version = "0.9.0"
requires-python = ">=3.11.0"
dependencies = [
    "transformers<4.51.0",
    "huggingface_hub[hf_xet]>=0.31",
    "litserve>=0.2.10",
    "lightning>=2.5.1.post0",
    "discord>=2.3.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "numpy==1.24",
    "datasets>=3.5.0",
    "jsonargparse>=4.38.0",
    "ipykernel>=6.29.5",
    "comet-ml>=3.49.7",
    "matplotlib>=3.10.1",
    "seaborn>=0.12.1",
]

[project.optional-dependencies]
cpu = [
  "torch==2.2.0",
]
cu128 = [
  "torch>=2.7.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true


