[project]
name = "toxy-bot"
version = "0.1.3"
description = "A trained Discord Bot to detect and handle toxic messages in text channels."
readme = "README.md"
authors = [
    { name = "anitamaxvim", email = "107803920+anitamaxvim@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = [
    "kagglehub>=0.3.10",
    "pandas>=2.2.3",
    "pydantic>=2.10.6",
    "scikit-learn>=1.6.1",
    "scikit-multilearn>=0.2.0",
    "tensorflow==2.16.2",
]

license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.scripts]
toxy-bot = "toxy_bot:main"
make_datasets = "toxy_bot.ml.data.pipeline:run_pipeline"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["pandas-stubs>=2.2.3.241126"]

