[project]
name = "model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cozmo", email = "107803920+Cozmo18@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "torch<2.3",
    "dotenv>=0.9.9",
    "lightning>=2.5.2",
    "litserve>=0.2.12",
    "numpy<2",
    "transformers>=4.52.4",
]

[project.scripts]
run = "model.server:main"
test-client = "model.client:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
